### ISSUE TITLE
how to convert the java file & use it in xcode project?

### ISSUE THREAD

**Issue by raymondChan23** [shim007/j2objc-pod#1]
after run pod install, 
there is j2objc-pod lib in the xcode project.
but how to convert my .java file and use it in xcode? thankssss

**Comment by shim007** [comment]
> after run pod install, there is j2objc-pod lib in the xcode project. but how to convert my .java file and use it in xcode? thankssss

不好意思，这个项目很久没维护了。
我是在java中通过maven导出jar包，并且保留源码，然后运行j2objc，在参数中设置jar包路径和java的classes路径，这样会自动生成对应的objc类。
然后将生成的代码放入objc工程中的目录引用。
由于生成的代码依赖相应的j2objc函数库，所以需要设置相关引用。
为了方便就提交了pod配置，方便在pod install的时候自动引入相应的依赖。
希望能帮助到你。

**Comment by shim007** [comment]
补充我在转换java文件时的命令，其中需要把第三方依赖也放进来
`/Users/admin/bin/j2objc27/j2objc -encoding UTF-8 --no-package-directories -use-arc -x objective-c  -sourcepath /Users/admin/Workspace/sxiotsdkshare/src/main/java  -d /Users/admin/Workspace/sxiotsdkshare/target/j2objc  -classpath /Users/admin/.m2/repository/com/.../1.6.5-SNAPSHOT/sxiotsdkshare-1.6.5-SNAPSHOT.jar:/Users/admin/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar  com/.../comm/lang/MD5Utils.java com/.../comm/lang/SpecialDataTool.java com/.../comm/lang/JSBaseTool.java \
 /Users/admin/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6-sources.jar`
